import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import { simulateStepwise } from "../domain/simulation";
import { buildSimResult } from "../domain/result";
import { hysteresisPolicy, neverPausePolicy } from "../domain/policy";
import { tokensPerSecond } from "../domain/physics";
import type { FullProfile, CO2Timeline, SimConfig, SimProgress } from "../domain/types";

/**
 * Regression test: TypeScript simulation output must match Python.
 *
 * Python reference generated by `src/main.py` (the "pilot run" CLI),
 * which uses the same physics constants and same policy logic.
 *
 * If this test fails, the TS simulation has drifted from the Python
 * implementation and needs investigation.
 */

// ---------------------------------------------------------------------------
// Reference data (Python output for Deepseek × CN × 4 years)
// ---------------------------------------------------------------------------

interface PythonRef {
  thetaPause: number;
  thetaResume: number;
  startTime: string;
  totalEmissionsKgco2: number;
  baselineEmissionsKgco2: number;
  actualOverheadPct: number;
  co2SavingsPct: number;
  numPauses: number;
  totalWallTimeH: number;
  trainingTimeH: number;
  pausedTimeH: number;
}

const PYTHON_REFS: PythonRef[] = [
  // θ_p=550, θ_r=500, start=01-01
  { thetaPause: 550, thetaResume: 500, startTime: "01-01",
    totalEmissionsKgco2: 1327020.4293160287, baselineEmissionsKgco2: 1319902.0512322676,
    actualOverheadPct: 134.3079078922835, co2SavingsPct: -0.53931108578211,
    numPauses: 89, totalWallTimeH: 3047.8333333333335, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 1743.3734164634275 },
  // θ_p=600, θ_r=550, start=01-01
  { thetaPause: 600, thetaResume: 550, startTime: "01-01",
    totalEmissionsKgco2: 1323754.6200778065, baselineEmissionsKgco2: 1319902.0512322676,
    actualOverheadPct: 23.52832831270369, co2SavingsPct: -0.29188293494521883,
    numPauses: 35, totalWallTimeH: 1606.8333333333333, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 304.60541646342426 },
  // θ_p=550, θ_r=500, start=02-18
  { thetaPause: 550, thetaResume: 500, startTime: "02-18",
    totalEmissionsKgco2: 1234140.5584181808, baselineEmissionsKgco2: 1255964.6347684753,
    actualOverheadPct: 62.504904889280326, co2SavingsPct: 1.7376346233122695,
    numPauses: 54, totalWallTimeH: 2113.8333333333335, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 810.8200831300917 },
  // θ_p=600, θ_r=550, start=02-18
  { thetaPause: 600, thetaResume: 550, startTime: "02-18",
    totalEmissionsKgco2: 1247223.9893515015, baselineEmissionsKgco2: 1255964.6347684753,
    actualOverheadPct: 6.769169153544546, co2SavingsPct: 0.6959308546601799,
    numPauses: 10, totalWallTimeH: 1388.8333333333333, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 87.63874979675784 },
  // θ_p=550, θ_r=500, start=06-01
  { thetaPause: 550, thetaResume: 500, startTime: "06-01",
    totalEmissionsKgco2: 1201235.2081762992, baselineEmissionsKgco2: 1193790.8642950356,
    actualOverheadPct: 12.534934919310311, co2SavingsPct: -0.6235886120354681,
    numPauses: 18, totalWallTimeH: 1463.8333333333333, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 162.30808313009115 },
  // θ_p=600, θ_r=550, start=06-01
  { thetaPause: 600, thetaResume: 550, startTime: "06-01",
    totalEmissionsKgco2: 1193790.8642950356, baselineEmissionsKgco2: 1193790.8642950356,
    actualOverheadPct: 0.0040039883793793795, co2SavingsPct: 0,
    numPauses: 0, totalWallTimeH: 1300.8333333333333, trainingTimeH: 1300.7812502032423,
    pausedTimeH: 0.05208313009114583 },
];

// ---------------------------------------------------------------------------
// Test fixture (matches Python's Deepseek profile + CN CO2 data)
// ---------------------------------------------------------------------------

const deepseek: FullProfile = {
  name: "Deepseek",
  modelParams: 671e9,
  datasetTokens: 14.8e12,
  gpuCount: 2048,
  gpuPowerTrain: 700,
  gpuPowerPause: 60,
  pue: 1.27,
  checkpointPauseTime: 148.8,
  checkpointResumeTime: 0,
};

describe("regression vs Python (CN, Deepseek, 4-year average)", () => {

  /**
   * Generate averaged CN timeline dynamically from the JSON file.
   * JSON is fetched lazily — if the file is missing, tests that
   * need it are skipped.
   */
  function loadCNTimeline(): CO2Timeline | null {
    try {
      const __dirname = dirname(fileURLToPath(import.meta.url));
      const filePath = resolve(__dirname, "../../public/data/co2/CN.json");
      const raw = readFileSync(filePath, "utf-8");
      return JSON.parse(raw) as CO2Timeline;
    } catch {
      return null;
    }
  }

  function checkPythonRef(ref: PythonRef) {
    const tl = loadCNTimeline();
    if (!tl) return; // skip if data unavailable

    const simConfig: SimConfig = {
      startTime: ref.startTime,
      historicalYears: [2022, 2023, 2024, 2025],
      overheadBudgetPct: 200,
    };

    // --- baseline (never-pause) ---
    const baselineProg: SimProgress[] = [];
    for (const p of simulateStepwise(deepseek, neverPausePolicy(), tl, simConfig)) {
      baselineProg.push(p);
    }
    const baselineLast = baselineProg[baselineProg.length - 1];

    // --- policy simulation ---
    const policy = hysteresisPolicy(ref.thetaPause, ref.thetaResume);
    const prog: SimProgress[] = [];
    for (const p of simulateStepwise(deepseek, policy, tl, simConfig)) {
      prog.push(p);
    }
    const last = prog[prog.length - 1];

    const result = buildSimResult(deepseek, simConfig, last, baselineLast,
      ref.thetaPause, ref.thetaResume, {
        id: "regression-test",
        scenarioDescription: "test",
        model: "Deepseek",
        region: "CN",
        timestamps: [],
        carbonIntensitySeries: [],
        stateSeries: [],
        emissionsSeries: [],
        tokensRemainingSeries: [],
      });

    expect(result.totalEmissionsKgco2)
      .toBeCloseTo(ref.totalEmissionsKgco2, 0);  // 0 decimal places ≈ 1 kg
    expect(result.baselineEmissionsKgco2)
      .toBeCloseTo(ref.baselineEmissionsKgco2, 0);
    expect(result.actualOverheadPct)
      .toBeCloseTo(ref.actualOverheadPct, 1);     // 1 decimal place
    expect(result.co2SavingsPct)
      .toBeCloseTo(ref.co2SavingsPct, 1);
    expect(result.numPauses).toBe(ref.numPauses);
    expect(result.totalWallTimeH)
      .toBeCloseTo(ref.totalWallTimeH, 1);
    expect(result.trainingTimeH)
      .toBeCloseTo(ref.trainingTimeH, 1);
    expect(result.pausedTimeH)
      .toBeCloseTo(ref.pausedTimeH, 1);
  }

  for (const ref of PYTHON_REFS) {
    it(`θ_p=${ref.thetaPause} θ_r=${ref.thetaResume} start=${ref.startTime}`, () => {
      checkPythonRef(ref);
    });
  }
});

// ---------------------------------------------------------------------------
// Structural invariants (should hold for any valid simulation)
// ---------------------------------------------------------------------------

describe("structural invariants (cross-referenced with Python)", () => {
  it("baseline emissions = policy emissions when θ_p=Infinity", () => {
    // A "policy" that never pauses should produce the same result
    // as the baseline simulation (trivially verified).
    const config: SimConfig = {
      startTime: "01-01",
      historicalYears: [2022],
      overheadBudgetPct: 200,
    };
    const tl: CO2Timeline = {
      zone: "DE", years: [2022],
      timestamps: ["2022-01-01T00:00:00Z", "2022-01-01T00:05:00Z"],
      carbonIntensity: [200, 200],
    };
    const profile: FullProfile = {
      name: "T", modelParams: 1e9, datasetTokens: 1e6, gpuCount: 1,
      gpuPowerTrain: 700, gpuPowerPause: 60, pue: 1,
      checkpointPauseTime: 0, checkpointResumeTime: 0,
    };

    const neverPause: SimProgress[] = [];
    for (const p of simulateStepwise(profile, neverPausePolicy(), tl, config)) neverPause.push(p);
    const lastNp = neverPause[neverPause.length - 1];

    const highTheta: SimProgress[] = [];
    const hp = hysteresisPolicy(9999, 0);
    for (const p of simulateStepwise(profile, hp, tl, config)) highTheta.push(p);
    const lastHt = highTheta[highTheta.length - 1];

    expect(lastNp.totalEmissionsG).toBe(lastHt.totalEmissionsG);
    expect(lastNp.numPauses).toBe(0);
    expect(lastHt.numPauses).toBe(0);
  });

  it("overhead strictly non-negative", () => {
    const tps = tokensPerSecond(1);
    expect(tps).toBeGreaterThan(0);
    const pausedS = 100, checkpointS = 50, tokens = 1e6;
    const overhead = 100 * (pausedS + checkpointS) / (tokens / tps);
    expect(overhead).toBeGreaterThan(0);
  });

  it("paused + training + checkpoint = wall time", () => {
    // This holds at every SimProgress yield by construction in the
    // generator, so we verify the invariant is correctly implemented.
    const config: SimConfig = {
      startTime: "01-01", historicalYears: [2022], overheadBudgetPct: 200,
    };
    const tl: CO2Timeline = {
      zone: "DE", years: [2022],
      timestamps: ["2022-01-01T00:00:00Z", "2022-01-01T00:05:00Z", "2022-01-01T00:10:00Z"],
      carbonIntensity: [100, 400, 50],
    };
    const profile: FullProfile = {
      name: "T", modelParams: 1e9, datasetTokens: 10_000_000, gpuCount: 1,
      gpuPowerTrain: 700, gpuPowerPause: 60, pue: 1,
      checkpointPauseTime: 0, checkpointResumeTime: 0,
    };
    const policy = hysteresisPolicy(300, 100);

    for (const p of simulateStepwise(profile, policy, tl, config)) {
      const wallSum = p.trainingS + p.pausedS + p.checkpointS;
      expect(Math.abs(p.totalWallS - wallSum)).toBeLessThan(0.01);
    }
  });
});
